apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: redis
data:
  redis.conf: |-
    bind 0.0.0.0
    protected-mode no
    port 6379
    tcp-backlog 511
    aclfile /etc/redis/users.acl
    timeout 0
    tcp-keepalive 300
    databases 1
    always-show-logo yes
    save 900 1
    save 300 10
    save 60 10000
    dir "/data"
