apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
spec:
{{- if ne .Values.env "prod" }}
  clusterIP: None
{{- else }}
  type: LoadBalancer
  loadBalancerIP: {{ .Values.redis.loadBalancerIP | default "192.168.86.98" | quote }}
{{- end }}
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis
