env: test

apps:
  fetcher:
    enabled: false
  repeater:
    enabled: true
  webdisplay:
    env:
      - name: REACT_APP_API_URL
        value: "http://theoden.pjis.net/api"
ingress:
  apiserver:
    host: theoden.pjis.net
  webdisplay:
    host: theoden.pjis.net
  dashboard:
    host: testdashboard.pjis.net
    namespace: kubernetes-dashboard
    serviceName: kubernetes-dashboard-kong-proxy
    port: 443

# test-specific redis overrides
redis:
  host: redis.redis
  image: "redis:alpine"
  storageClassName: microk8s-hostpath
