classDiagram
    class RedisClient <<abstract>> {
        -client Redis.client
        -in_channel str
        -out_channel str
        -redis_thread thread
        -redis_liveness_server HTTPServer
        -redis_liveness_thread thread
        _get_redis_url() str
        _get_prod_redis_url() str
        connect_redis(redis_url: str = None)
        +rget(key, prod: bool = False)
        +rset(key, value, prod: bool = False)
        +publish(message, prod: bool = False)
        +listen(channel, prod: bool = False)
        message_handler(message)*
        _shutdown_service(signum)
    }
    class HealthHandler {
        do_GET()
    }
    RedisClient *-- HealthHandler
    class Redis {
        client
    }
    RedisClient *-- Redis
    class Fetcher {
        secrets dict
        timezone str
        urls dict
        headers dict
        scheduler Scheduler
        client RedisClient
        lat_long str
        read_secrets() dict
        build_urls() dict
        build_headers() dict
        message_handler(message) %% Actually unused, but must be overridden
        update_period(type, period)
        dispatcher(type)
        fetch(url: str, message: str, now: str, headers: dict = None, raw: bool = False)
        aqi(url: str, timezone: str) dict
        events() list[dict]
        gcal(url: str, timezone: str) dict
        mlb(url: str, timezone: str) list[dict]
        moon(url: str, timezone: str, headers: dict, lat_long: str) list[dict]
        nfl(url: str, timezone: str) dict
        weather(url: str, timezone: str) dict
        run()
    }
    Fetcher ..|> RedisClient
    class SecretManager {
        SOURCES set
        k8s_client
        hvac_client
        config dict
        registry VerbRegistry
        ~__init__(config: dict = None)
        +configure_secret_type(config)
        +execute(backend, verb)
    }
    Fetcher *-- SecretManager
    class _kubevault_ops {
        init_kubevault(manager: SecretManager)
        reauthenticate_vault_via_kubernetes(manager: SecretManager) bool
        read_encrypted_secrets(manager: SecretManager, secret_def: dict) dict
        create_encrypted_secret(manager: SecretManager, secret_def: dict, data: str) dict
        rotate_vault_key(manager: SecretManager, transit_key: str) dict
        logout_kubevault(manager: SecretManager) dict
    }
    SecretManager *-- _kubevault_ops
    class _k8s_ops {
        connect_to_k8s(manager: SecretManager) client.CoreV1Api
        _get_k8s_service_account_token(k8s_client, service_account, namespace) jwt
        create_k8s_secret(manager: SecretManager, secret_def: dict, data) dict
        read_k8s_secret(manager: SecretManager, secret_def: dict)
        logout_k8s(manager: SecretManager) dict
    }
    _kubevault_ops *-- _k8s_ops
    class _vault_ops {
        connect_to_vault(url, verify: bool = True) hvac_client
        _authenticate_vault_via_kubernetes(hvac_client, role, jwt)
        encrypt_data_with_vault(hvac_client, transit_key, data)
        decrypt_data_with_vault(hvac_client, transit_key, data)
        _rotate_vault_key(hvac_client, transit_key)
        logout_vault(hvac_client)
    }
    _kubevault_ops *-- _vault_ops
    class VerbRegistry {
        VERBS set
        ~__init__(SECRET_VERB_REGISTRY)
        get_handler(source, verb) callable
        list_sources() list
        list_verbs(source) list
        validate()
        perform(backend, verb)
        safe_get_handler(backend, verb)
    }
    SecretManager *-- VerbRegistry
    class Scheduler {
        notifier callable
        timezone str
        config dict
        queue list
        configured_types() list
        dump_queue()
        set_period(type: str, period: int)
        schedule_next_run(type, now, Reschedule)
        now_str(t: arrow, local: bool = False)
        run()
    }
    Fetcher *-- Scheduler
    %% class Repeater {
    %%     client RedisClient
    %%     prod_client RedisClient
    %% }
    %% Repeater ..|> RedisClient
    class KV-Updater {
        client RedisClient
        message_handler(message)
    }
    KV-Updater ..|> RedisClient
    %% class Recorder {
    %%     client RedisClient
    %%     message_handler(message)
    %% }
    %% Recorder ..|> RedisClient
    class Transformer {
        client RedisClient
        type str
        timezone str
        message_handler(message)
        update(data)*
        run()
    }
    Transformer ..|> RedisClient
    class Events {
        type str = 'Events'
        update(data)
    }
    Events <|-- Transformer
    class CalendarServer {
        type str = 'Calendar'
        update(data)
    }
    CalendarServer <|-- Transformer
    class AQI {
        type str = 'AQI'
        AQIData dict
        update(data)
        _convert_reading(value, pollutant)
        _scaled_reading(value, pollutant)
    }
    AQI <|-- Transformer
    class Moon {
        type str = 'Moon'
        update(data)
        _moon_condition(moonphase float)
        _sun_event(mnd list, tstmp) str
        _moon_event(mnd list) str
        _age_to_illum(age int) float
        _parse_time(timestr str) arrow
        _ts2hhmm(tstmp) str
    }
    Moon <|-- Transformer
    class Weather {
        type str = 'Weather'
        dirs list
        update(data)
        _to_nwid(icon,wid)
        _deg_to_dir(degrees)
    }
    Weather <|-- Transformer
    class MLB {
        type str = 'MLB'
        update(data)
        _load_game(game)
        _team_values_and_scores(competition)
    }
    MLB <|-- Transformer
    class NFL {
        type str = 'NFL'
        update(data)
        _read_event(event)
    }
    NFL <|-- Transformer